### ISSUE TITLE
Is accessing out of bound index in array dangerous in Solidity?

### ISSUE THREAD

**Issue by ciasom** [TokenMarketNet/ico#101]
1. In contract MilestonePricing's constructor, if milestoneCount==0, milestones[milestoneCount-1] will try to access index -1 or maybe very large number (not sure).
2. If an address is not in preicoAddresses, and now is less than the first milestone, then milestones[i-1] in function getCurrentMilestone will also try to access -1 or maybe very large number.

Contract EthTranchePricing has similar issues.

I'm not sure if Solidity deals with such exceptions and didn't find related information in the docs.

**Comment by miohtama** [comment]
@villesundell I think it should return zero?

**Comment by ciasom** [comment]
It looks solidity throws when trying to access out of bound index. So much safer than that in C/C++.
