### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by rstormsf** [TokenMarketNet/ico#11]
I did `pip3 install -r requirements.txt` but how do I get `presale` CLI ? 

Also ran `python3 setup.py install` and checked  `venv/bin` folder it does have `deploy-presale` binary, but the docs say to run `presale` I assume it's the same

when I tried to use `deploy-presale`, it gives me an error:

`ModuleNotFoundError: No module named 'ico.cmd'`

**Comment by miohtama** [comment]
Try:

`pip install -e .`

**Comment by rstormsf** [comment]
@miohtama same thing. `ModuleNotFoundError: No module named 'ico.cmd' `

Can I call you ? or pair program? Would really love to set it up.

**Comment by rstormsf** [comment]
Or if you could try on your own Mac from scratch to document all installation steps, it would be really helpful for the community

**Comment by miohtama** [comment]
I would love to help and set up some pair programming. However, unfortunately my personal situation does not allow to take any extra tasks at the moment.

We are getting more people on the deck, so the situation should improve in some point. Currently this project is mostly limited to industry experts.

**Comment by rstormsf** [comment]
After careful installation of Populus and thier issue with https://github.com/pipermerriam/populus/issues/301 Now everything works fine with CLI tools. 
My issue resolved.

**Comment by rstormsf** [comment]
```
Source "zeppelin/contracts/ownership/Ownable.sol" not found: Unknown exception in read callback.
import "zeppelin/contracts/ownership/Ownable.sol";
```
