### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mikechn** [TokenMarketNet/ico#110]
when I ran this in Ubuntu:
git clone --recursive git@github.com:TokenMarketNet/ico.git

I got :

Cloning into 'ico'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by chut** [comment]
This is a problem with your key setup in your Github account. Should be able to address it by looking at GitHub's help. https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
