### ISSUE TITLE
IPC timeout

### ISSUE THREAD

**Issue by iojupiter** [TokenMarketNet/ico#12]
Is there a way to specify my geth ipc endpoint?
I get an ipc timeout (60 seconds) after running `deploy-token --chain ropsten`
My ropsten blockchain (consequently the geth.ipc file) is running in another directory

Thank you

**Comment by miohtama** [comment]
Edit `populus.json` file. Endpoints are listed there by chain name. 

Hope this helps?

**Comment by iojupiter** [comment]
This is what I understood your software does, but should the ipc file of my geth instance be in the current working directory of your project?

**Comment by iojupiter** [comment]
Alright, I managed to connect to my geth instance by changing endpoint in `populus.json` file from :8546 to port number :8545 (default geth port number). On the command line I removed `--chain=ropsten` when trying `deploy-token`
