### ISSUE TITLE
eth_utils throws "force_text" Error

### ISSUE THREAD

**Issue by blackmoneycoin** [TokenMarketNet/ico#120]
When calling deploy-contracts an error is thrown:

  from populus import Project
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'

Same error is thrown when calling 'populus compile'... 

Here is my pip list:

anyconfig (0.9.4)
argh (0.26.2)
astroid (1.6.1)
attrdict (2.0.0)
attrs (17.4.0)
bitcoin (1.1.42)
certifi (2018.1.18)
cffi (1.11.5)
chardet (3.0.4)
click (6.7)
contextlib2 (0.5.5)
cytoolz (0.9.0)
eth-abi (1.0.0)
eth-account (0.1.0a2)
eth-hash (0.1.0)
eth-keyfile (0.5.1)
eth-keys (0.2.0b3)
eth-rlp (0.1.0)
eth-tester (0.1.0b11)
eth-testrpc (1.3.3)
eth-utils (1.0.1)
ethereum (1.6.1)
ethereum-abi-utils (0.4.0)
ethereum-serpent (2.0.7)
ethereum-utils (0.3.2)
ethjsonrpc (0.1)
hexbytes (0.1.0)
ico (0.1, /Users/edthomas/Projects/coin)
idna (2.6)
isort (4.3.4)
Jinja2 (2.10)
json-rpc (1.10.8)
jsonschema (2.6.0)
lazy-object-proxy (1.3.1)
lru-dict (1.1.6)
MarkupSafe (1.0)
mccabe (0.6.1)
pathtools (0.1.2)
pbkdf2 (1.3)
pip (9.0.1)
pluggy (0.6.0)
populus (2.2.0)
py (1.5.2)
py-geth (2.0.1)
py-solc (2.1.0)
pycparser (2.18)
pycryptodome (3.4.11)
pyethash (0.1.27)
pylint (1.8.2)
pylru (1.0.9)
pysha3 (1.0.2)
pytest (3.4.2)
PyYAML (3.12)
repoze.lru (0.7)
requests (2.18.4)
rlp (0.6.0)
ruamel.yaml (0.15.35)
scrypt (0.8.6)
secp256k1 (0.13.2)
semantic-version (2.6.0)
setuptools (38.5.1)
six (1.11.0)
toolz (0.9.0)
toposort (1.5)
urllib3 (1.22)
virtualenv (15.1.0)
watchdog (0.8.3)
web3 (4.0.0b11)
Werkzeug (0.14.1)
wrapt (1.10.11)

Thanks for your support

Ed

**Comment by petri** [comment]
Related: 

- https://github.com/ethereum/populus/issues/450
- https://github.com/ethereum/populus/issues/447
- https://github.com/ethereum/eth-utils/issues/81

**Comment by petri** [comment]
Making sure web3 is e.g. == 3.16.5 fixed the issue for me.
