### ISSUE TITLE
populus.utils.compat.compat_stdlib.Timeout: 120 seconds

### ISSUE THREAD

**Issue by troowala** [TokenMarketNet/ico#133]
I have also tried increasing the timeout from 180 to 18000 in populus.json but it seems this parameter is being ignored as the value specified here is not being considered no matter what it is set to.

Issue occurs only when deploying to mainnet. Ropsten & Local deployments work fine. 

Still seems to be deploying the SafeMathLib contract needed as part of the token contract just fine but fails after that Same issue doesnt happen when deploying to ropsten even though Mainnet chain is synced and wallet is unlocked just like ropsten.

where else can i investigate ? 

thanks for your help.

python3 ico/cmd/deploycontracts.py --deployment-file crowdsales/WHT_PRIVATE.yml --deployment-name WHT-token --address 0x3a514b826d8235dfbfc7e67f9d7f6173e9c109ed

Web3 provider is RPC connection http://172.21.0.1:8545
Owner address is 0x3a514b826d8235dfbfc7e67f9d7f6173e9c109ed
Owner balance is 2.4392779656494 ETH
Already deployed contract, team_multisig 0x46cf3064b571bfb48367182764c5e5d2e02e3733
Starting BurnableCrowdsaleToken deployment, with arguments  {'_name': 'Whatever', '_decimals': 18, '_initialSupply': 0, '_symbol': 'WHT', '_mintable': True}
Traceback (most recent call last):
  File "/usr/src/app/ico/deploy.py", line 66, in deploy_contract
    contract, txhash = chain.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 115, in deploy_contract
    self.get_or_deploy_contract(dependency_name, deploy_transaction=deploy_transaction)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 143, in get_or_deploy_contract
    deploy_kwargs=deploy_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 123, in deploy_contract
    contract_address = self.chain.wait.for_contract_address(deploy_transaction_hash)
  File "/usr/local/lib/python3.5/dist-packages/populus/wait.py", line 33, in for_contract_address
    txn_receipt = self.for_receipt(txn_hash, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/populus/wait.py", line 47, in for_receipt
    return wait_for_transaction_receipt(self.web3, txn_hash, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/populus/utils/wait.py", line 34, in wait_for_transaction_receipt
    poll_interval_fn=lambda: poll_interval if poll_interval is not None else random.random(),
  File "/usr/local/lib/python3.5/dist-packages/populus/utils/wait.py", line 22, in poll_until
    _timeout.sleep(poll_interval_fn())
  File "/usr/local/lib/python3.5/dist-packages/populus/utils/compat/compat_stdlib.py", line 74, in sleep
    self.check()
  File "/usr/local/lib/python3.5/dist-packages/populus/utils/compat/compat_stdlib.py", line 67, in check
    raise self
populus.utils.compat.compat_stdlib.Timeout: 120 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ico/cmd/deploycontracts.py", line 34, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "ico/cmd/deploycontracts.py", line 29, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/usr/src/app/ico/deploy.py", line 286, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/usr/src/app/ico/deploy.py", line 270, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, yaml_filename, chain_data, deploy_address)
  File "/usr/src/app/ico/deploy.py", line 133, in deploy_crowdsale
    contracts[name] = deploy_contract(project, chain, deploy_address, expanded_contract_def, chain_name, need_unlock=need_unlock)
  File "/usr/src/app/ico/deploy.py", line 68, in deploy_contract
    raise RuntimeError("Could not deploy contract {}, constructor arguments {}".format(contract_name, kwargs)) from e
RuntimeError: Could not deploy contract BurnableCrowdsaleToken, constructor arguments {'_name': 'Whatever', '_decimals': 18, '_initialSupply': 0, '_symbol': 'WHT', '_mintable': True}

----- populus.json ---

  "chains": {
    "mainnet": {
      "chain": {
        "class": "populus.chain.external.ExternalChain"
      },
      "contracts": {
        "backends": {
          "JSONFile": {
            "$ref": "contracts.backends.JSONFile"
          },
          "Memory": {
            "$ref": "contracts.backends.Memory"
          },
          "ProjectContracts": {
            "$ref": "contracts.backends.ProjectContracts"
          },
          "TestContracts": {
            "$ref": "contracts.backends.TestContracts"
          }
        }
      },
      "web3": {
        "provider": {
          "class": "web3.providers.rpc.HTTPProvider",
          "settings": {
            "endpoint_uri": "http://172.21.0.1:8545",
            "request_kwargs": {
                "timeout": 180
            }
          }
        }
      }
    },
     "ropsten": {
      "chain": {
        "class": "populus.chain.external.ExternalChain"
      },
      "contracts": {
        "backends": {
          "JSONFile": {
            "$ref": "contracts.backends.JSONFile"
          },
          "Memory": {
            "$ref": "contracts.backends.Memory"
          },
          "ProjectContracts": {
            "$ref": "contracts.backends.ProjectContracts"
          },
          "TestContracts": {
            "$ref": "contracts.backends.TestContracts"
          }
        }
      },
      "web3": {
        "provider": {
          "class": "web3.providers.rpc.HTTPProvider",
          "settings": {
            "endpoint_uri": "http://172.21.0.1:8545",
            "request_kwargs": {
                "timeout": 180
            }
          }
        }
      }
    }

**Comment by petri** [comment]
This is probably because of Populus that sets default timeouts in a few places. See https://github.com/ethereum/populus/search?q=timeout&unscoped_q=timeout .

**Comment by voith** [comment]
I have opened https://github.com/ethereum/populus/pull/464 to fix this issue

**Comment by troowala** [comment]
is there a workaround/solution in the interim to address this ?

**Comment by voith** [comment]
@troowala Let me see if I can monkey match some code in the `ico` repo to increase the timeout.

**Comment by troowala** [comment]
thanks mate , i have tried increasing every timeout value in every file in the ico directory by 100X but still get the same issue. also ocassionally some contracts do end up deploying and then it bails halfway through with these timeout issues on mainnet but never on ropsten. 

im not even using the confirm_tx option so why would it behave this way ? should it not simply submit the transaction get tx hash and proceed ? 

also any way to use infura or ipc instead of http provider , the populus.json doesnt get into passing the private key to infura node option nor into using an ipc path . thanks for your time on this.

**Comment by voith** [comment]
@troowala I have opened #136 to resolve the issue.

>  also any way to use infura 

I'm fairly new to the project, so my answers might be wrong here. But from my quick read through the codebase, I think you have specify `chain` in your yaml file. eg: https://github.com/TokenMarketNet/ico/blob/c8d45fa4117bcb7caf756c5c3ecf736e0c3759d2/crowdsales/unit-test.yml#L7

>  or ipc instead of http provider

I don't think that's possible at the moment. But we could make that configurable too. Let me leave this decision to @miohtama.

**Comment by troowala** [comment]
in the interim the workaround was to change the timeout values in the following files
/usr/local/lib/python3.5/dist-packages/populus/wait.py
/usr/local/lib/python3.5/dist-packages/populus/utils/wait.pu

**Comment by voith** [comment]
@troowala changing timeout in just `populus/wait.py` wasn't sufficient?  Why did you need to change values in `populus/utils/wait.py`?

**Comment by troowala** [comment]
it looked like it was leveraging timeout values from both in different scenarios/stages of the deploy so i did, do you reckon only populus/wait.py requires the changes ?

**Comment by voith** [comment]
@troowala `populus/wait.py` should be sufficient. All the methods are in `populus/wait.py` are drived through [Wait](https://github.com/ethereum/populus/blob/d18ac1785cc575671baada62e594d7ab7997003d/populus/wait.py#L11) class in `populus/wait.py`. So just setting values in `populus/wait.py` should be sufficient.
