### ISSUE TITLE
using tokenmarket tools with infura

### ISSUE THREAD

**Issue by troowala** [TokenMarketNet/ico#141]
Hello,

Is using infura for the geth node supported with tokenmarket tools ? 

I do see the option in the included populus.json which has InfuraRopsten. However when specifying this as the chain i get the error

```
KeyError: "Unknown chain: 'InfuraRopsten' - Must be one of ['ganache', 'kovan', 'local', 'mainnet', 'ropsten', 'temp', 'tester', 'testrpc']"
```

When trying to specify the infura URL https://ropsten.infura.io/v3/myapikeyherexxxxxx as the endpoint_uri in one of the above chains for example ropsten i get the below error , so just wanted to check if infura as a provider is supported or not and if so then where is the private key to be specified for the address publishing the contracts.

thanks for your help. 

```
root@d984d1e5b661:/usr/src/app# python3 ico/cmd/deploycontracts.py --deployment-file crowdsales/EST_TSE.yml --deployment-name EST-token --address 0x88d4c3A4299a3EdB91AA04147A2380F263E94E4F
Web3 provider is RPC connection https://ropsten.infura.io
Owner address is 0x88d4c3A4299a3EdB91AA04147A2380F263E94E4F
Owner balance is 5.172827807140385597 ETH
Already deployed contract, team_multisig 0xCd9d9E52a40aB92a102CB9fB05843b8D50b3B17e
Traceback (most recent call last):
  File "ico/cmd/deploycontracts.py", line 34, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "ico/cmd/deploycontracts.py", line 29, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/usr/src/app/ico/deploy.py", line 286, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/usr/src/app/ico/deploy.py", line 270, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, yaml_filename, chain_data, deploy_address)
  File "/usr/src/app/ico/deploy.py", line 133, in deploy_crowdsale
    contracts[name] = deploy_contract(project, chain, deploy_address, expanded_contract_def, chain_name, need_unlock=need_unlock)
  File "/usr/src/app/ico/deploy.py", line 47, in deploy_contract
    if is_account_locked(web3, deploy_address):
  File "/usr/local/lib/python3.5/dist-packages/populus/utils/accounts.py", line 15, in is_account_locked
    web3.eth.sign(account, 'simple-test-data')
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 262, in sign
    "eth_sign", [account, encode_hex(data)],
  File "/usr/local/lib/python3.5/dist-packages/web3/providers/manager.py", line 27, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/usr/local/lib/python3.5/dist-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/compat/compat_requests.py", line 22, in make_post_request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://ropsten.infura.io/
````

**Comment by voith** [comment]
> KeyError: "Unknown chain: 'InfuraRopsten' - Must be one of ['ganache', 'kovan', 'local', 'mainnet', 'ropsten', 'temp', 'tester', 'testrpc']"

The error message tells you that the name of the InfuraRopsten is `ropsten`.
In your `crowdsales/EST_TSE.yml` set chain to ropsten

>  Method Not Allowed for url: https://ropsten.infura.io/

This means that `eth_Sign` is not supported on ropsten.  Our current codebase does not support ropsten well.

**Comment by troowala** [comment]
@voith thanks for your response. 

Im happy to use rinkeby or mainnet as long as i can use infura URL as the provider. However im unable to find where i could specify the private key to be used if using in conjunction with infura ? 

with a geth node im running i have the luxury of unlocking the wallet of a wallet file available on the geth node but with infura the transactions need to be signed by the private key first as there is no way to upload or unlock the wallet. 

How does one get around this with tokenmarket tools using infura as a provider ? Where can i specify the private key to be used ? Thanks

**Comment by voith** [comment]
clone the ico repo and change the following line to point to infura

https://github.com/TokenMarketNet/ico/blob/d80e6d1afe8569512e0b53e6e927354ef476b7bf/populus.json#L161
and then use the ropsten chain in your yaml.

Although we have a setting for `InfuraRopsten` it is not defined as a chain. I don't know how to use that. But my workaround should work for you

**Comment by voith** [comment]
> Where can i specify the private key to be used 

AFAIK, All account management is done assuming that you're connected to a local node, a node that supports the `personal` module.

Infura doesn't support the `personal` module. I don't think you can use the tokenmarket tools for working with infura.

cc @villesundell. Please correct me If I'm wrong!

**Comment by villesundell** [comment]
@voith That's correct, we can't support Infura for now, since we are relying the node itself to sign the transactions.

**Comment by troowala** [comment]
@villesundell  thanks for clarifying this. 
@voith yes i have tried that but run into the next issue which is the signing. 
thanks though for your time and responses . okay to close this for now.
