### ISSUE TITLE
Quick token sale walkthrough

### ISSUE THREAD

**Issue by saitam1** [TokenMarketNet/ico#143]
Is this picture on your Github channel main page correct?
![pic](https://user-images.githubusercontent.com/23245678/45318570-9e674280-b53d-11e8-9dda-8a39e112bbdc.png)

Failure = minimum funding goal NOT reached
Success = minimum funding goal NOT reached

Why is it successful if the funding goal was **NOT** reached?

**Comment by miohtama** [comment]
It is a typo in the image.
