### ISSUE TITLE
Remove SafeMathLib to use with zeppelin SafeMath

### ISSUE THREAD

**Issue by rstormsf** [TokenMarketNet/ico#16]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/SafeMath.sol - already provides it. No need to have your own.
If you agree, I can open a PR.

**Comment by miohtama** [comment]
Please do. This repository was created prior OpenZeppelin adopting this library. However they went and changed function names, so all contracts must be updated to use new function names.

**Comment by rstormsf** [comment]
curious to learn how do you run `tox` tests locally. Getting some issues on my mac, prob some missing configuration that I haven't run. Need to figure that out before I do any PR

**Comment by gelinger777** [comment]
IMHO needs to be closed

**Comment by miohtama** [comment]
Resolved.
