### ISSUE TITLE
how to use your example.yml file

### ISSUE THREAD

**Issue by rstormsf** [TokenMarketNet/ico#17]
https://github.com/TokenMarketNet/ico/blob/master/crowdsales/example.yml 
This file provides some good example on how to pass arguments and use your contract.
Would love to get some info on how do you use it

**Comment by miohtama** [comment]
Thanks. I'll update this example and the documentation tomorrow.

**Comment by miohtama** [comment]
There is now another example available. Also the current example has been updated.
