### ISSUE TITLE
Fix wrong comment that is not supported by latest solc 0.4.11

### ISSUE THREAD

**Issue by rstormsf** [TokenMarketNet/ico#19]
New solidity compiler gives an error for
https://github.com/TokenMarketNet/ico/blob/master/contracts/FlatPricing.sol#L23

```
: Documented parameter "{uint"
```

It's just reference for tomorrow's PR that I'm going to provide.

**Comment by gelinger777** [comment]
Solc 0.4.11 is not supported yet. You will have to manually build and use solc 0.4.8 as described in documentation.

**Comment by miohtama** [comment]
Fixed in the latest solc branch.
