### ISSUE TITLE
Crowdsale example.yml is missing arguments

### ISSUE THREAD

**Issue by rstormsf** [TokenMarketNet/ico#20]
https://github.com/TokenMarketNet/ico/blob/master/crowdsales/example.yml#L75 
Seems like there are 2 more that have to be added:
_decimals,
_mintable

**Comment by asleischow** [comment]
Where did you set the supply?? If using this code, once people have sent their funds to my wallet, will they receive their new coins automatically?

**Comment by gelinger777** [comment]
@asleischow I think no.  This crowdsale is engineered in a way, that people will get tokens when crowdsale is over, and tokens are distributed via special script.

**Comment by miohtama** [comment]
Fixed in 13dfd9afe3da8aa4311ef7c3c52b7d7fd601444a
