### ISSUE TITLE
Where to decide price?

### ISSUE THREAD

**Issue by senzacionale** [TokenMarketNet/ico#23]
Can we somehow set deadline and price, so how many new token you will get with 1 ETH?

```
fundingGoal = fundingGoalInEthers * 1 ether;

deadline = now + durationInMinutes * 1 minutes;

price = etherCostOfEachToken * 1 ether;
```

**Comment by villesundell** [comment]
There is a separate contract called a "pricing strategy" which is plugged into the main Crowdsale smart contract upon deployment. The Crowdsale will ask the PricingStrategy the price for every new investment. You can either use the current ones (FlatPricing, MilestonePricing, EthTranchePricing or TokenTranchePricing), or create your own by inheriting from PricingStrategy.sol. The ultimate deadline (crowdsale closing) is determined by the Crowdsale contract, and not the PricingStrategy.
