### ISSUE TITLE
Jupiter Error

### ISSUE THREAD

**Issue by gelinger777** [TokenMarketNet/ico#30]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-92dc85590f42> in <module>()
     29 with project.get_chain(chain_name) as chain:
     30 
---> 31     Contract = chain.get_contract_factory("CrowdsaleToken")
     32     contract = Contract(address=contract_address)
     33 

/usr/local/lib/python3.5/dist-packages/populus/chain/base.py in get_contract_factory(self, contract_identifier, link_dependencies)
    194                 "`Memory` contract backend prior to linking"
    195             )
--> 196         return self.provider.get_contract_factory(contract_identifier)
    197 
    198     def is_contract_available(self,

/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py in get_contract_factory(self, contract_identifier)
    235             return self._factory_cache[contract_identifier]
    236 
--> 237         BaseContractFactory = self.get_base_contract_factory(contract_identifier)
    238 
    239         bytecode = self._link_bytecode(BaseContractFactory.bytecode)

/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py in get_base_contract_factory(self, contract_identifier)
    187         The `bytecode` and `bytecode_runtime` will be unlinked in this class.
    188         """
--> 189         return get_base_contract_factory(contract_identifier, self.provider_backends)
    190 
    191     def get_contract_data(self, contract_identifier):

/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py in get_base_contract_factory(contract_identifier, store_backends)
     30     for _, backend in store_backends.items():
     31         try:
---> 32             return backend.get_base_contract_factory(contract_identifier)
     33         except UnknownContract:
     34             pass

/usr/local/lib/python3.5/dist-packages/populus/contracts/backends/base.py in get_base_contract_factory(self, contract_name)
     71             )
     72 
---> 73         contract_data = self.get_contract_data(contract_identifier)
     74 
     75         base_contract_factory = construct_contract_factory(

/usr/local/lib/python3.5/dist-packages/populus/contracts/backends/base.py in get_contract_data(self, contract_name)
     92         contract_identifier = self.get_contract_identifier(contract_name)
     93         try:
---> 94             return self.get_all_contract_data()[contract_identifier]
     95         except KeyError:
     96             raise UnknownContract(

/usr/local/lib/python3.5/dist-packages/populus/contracts/backends/project.py in get_all_contract_data(self)
     28             contract_name: contract_data
     29             for contract_name, contract_data
---> 30             in self.chain.project.compiled_contract_data.items()
     31             if is_project_contract(self.chain.project.contracts_source_dir, contract_data)
     32         }

/usr/local/lib/python3.5/dist-packages/populus/project.py in compiled_contract_data(self)
    243             _, self._cached_compiled_contracts = compile_project_contracts(
    244                 project=self,
--> 245                 compiler_settings=self.config.get('compilation.settings'),
    246             )
    247         return self._cached_compiled_contracts

/usr/local/lib/python3.5/dist-packages/populus/compilation.py in compile_project_contracts(project, compiler_settings)
     52 
     53     try:
---> 54         compiled_contracts = compile_files(all_source_paths, **compiler_settings)
     55     except ContractsNotFound:
     56         return all_source_paths, {}

/usr/local/lib/python3.5/dist-packages/solc/main.py in compile_files(source_files, allow_empty, output_values, **kwargs)
    121     compiler_kwargs = dict(source_files=source_files, combined_json=combined_json, **kwargs)
    122 
--> 123     stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
    124 
    125     contracts = _parse_compiler_output(stdoutdata)

/usr/local/lib/python3.5/dist-packages/solc/utils/string.py in inner(*args, **kwargs)
     65     @functools.wraps(fn)
     66     def inner(*args, **kwargs):
---> 67         return force_obj_to_text(fn(*args, **kwargs))
     68     return inner

/usr/local/lib/python3.5/dist-packages/solc/wrapper.py in solc_wrapper(solc_binary, stdin_bytes, help, version, add_std, combined_json, optimize, optimize_runs, libraries, output_dir, gas, assemble, link, source_files, import_remappings, ast, ast_json, asm, asm_json, opcodes, bin, bin_runtime, clone_bin, abi, interface, hashes, userdoc, devdoc, formal, success_return_code)
    140                             stdin=stdin,
    141                             stdout=subprocess.PIPE,
--> 142                             stderr=subprocess.PIPE)
    143 
    144     stdoutdata, stderrdata = proc.communicate()

/usr/lib/python3.5/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds)
    945                                 c2pread, c2pwrite,
    946                                 errread, errwrite,
--> 947                                 restore_signals, start_new_session)
    948         except:
    949             # Cleanup if the child failed starting.

/usr/lib/python3.5/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1549                             else:
   1550                                 err_msg += ': ' + repr(orig_executable)
-> 1551                     raise child_exception_type(errno_num, err_msg)
   1552                 raise child_exception_type(err_msg)
   1553 

FileNotFoundError: [Errno 2] No such file or directory: 'solc'

In [ ]:

​But Solc is installed as described in installation doc, manually, versio 0.4.8

**Comment by villesundell** [comment]
Hello there! :)
What is the code/command you try to run (with command line arguments, if any)?
Also, please paste here the output of "solc --version" when run from the command prompt.

**Comment by gelinger777** [comment]
hi @villesundell  I am trying to  interact with deployed contract to release it.  Solc is installed .

https://ico.readthedocs.io/en/latest/install.html as described here

**Comment by gelinger777** [comment]
seems I have fixed the issue.... There was a  PATH problem...

**Comment by gelinger777** [comment]
but now I get 

--------------------------------
NoKnownAddressTraceback (most recent call last)
<ipython-input-1-b9a4c6f9c531> in <module>()
     28 
     29     transaction = {"from": owner_address}
---> 30     Contract = chain.get_contract_factory("CrowdsaleToken")
     31 
     32     contract = Contract(address=contract_address)

/usr/local/lib/python3.5/dist-packages/populus/chain/base.py in get_contract_factory(self, contract_identifier, link_dependencies)
    194                 "`Memory` contract backend prior to linking"
    195             )
--> 196         return self.provider.get_contract_factory(contract_identifier)
    197 
    198     def is_contract_available(self,

/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py in get_contract_factory(self, contract_identifier)
    237         BaseContractFactory = self.get_base_contract_factory(contract_identifier)
    238 
--> 239         bytecode = self._link_bytecode(BaseContractFactory.bytecode)
    240         bytecode_runtime = self._link_bytecode(BaseContractFactory.bytecode_runtime)
    241 

/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py in _link_bytecode(self, bytecode)
    266             in find_link_references(
    267                 bytecode,
--> 268                 self.get_all_contract_names(),
    269             )
    270         ))

/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py in <genexpr>(.0)
    263         resolved_link_references = tuple((
    264             (link_reference, self.chain.provider.get_contract(link_reference.full_name).address)
--> 265             for link_reference
    266             in find_link_references(
    267                 bytecode,

/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py in get_contract(self, contract_identifier)
    107     def get_contract(self, contract_identifier):
    108         ContractFactory = self.get_contract_factory(contract_identifier)
--> 109         contract_addresses = self.chain.registrar.get_contract_addresses(contract_identifier)
    110 
    111         bytecode_matched_addresses = filter_addresses_by_bytecode_match(

/usr/local/lib/python3.5/dist-packages/populus/contracts/registrar.py in get_contract_addresses(self, contract_identifier)
     49         found_addresses = self._get_contract_addresses_from_backends(contract_identifier)
     50         if not found_addresses:
---> 51             raise NoKnownAddress("No known address for contract")
     52 
     53         if len(found_addresses) == 1:

NoKnownAddress: No known address for contract

**Comment by gelinger777** [comment]
i was trying to run 

```
import populus
from populus.utils.accounts import is_account_locked
from populus.utils.cli import request_account_unlock
from eth_utils import from_wei
from ico.utils import check_succesful_tx

# Which network we deployed our contract
chain_name = "mainnet"

# Owner account on geth
owner_address = "0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9"

# Where did we deploy our token
contract_address = "0x76d01f18EC70EF8c160377D50953915542e2493A"

project = populus.Project()

with project.get_chain(chain_name) as chain:

    web3 = chain.web3
    print("Web3 provider is", web3.currentProvider)
    print("Owner address is", owner_address)
    print("Owner balance is", from_wei(web3.eth.getBalance(owner_address), "ether"), "ETH")

    # Goes through geth account unlock process if needed
    if is_account_locked(web3, owner_address):
        request_account_unlock(chain, owner_address, None)

    transaction = {"from": owner_address}
    Contract = chain.get_contract_factory("CrowdsaleToken")

    contract = Contract(address=contract_address)
    print("Attempting to release the token transfer")
    txid = contract.transact(transaction).releaseTokenTransfer()
    check_succesful_tx(web3, txid)
    print("Token released")
```

**Comment by miohtama** [comment]
Can you change line 

       Contract = chain.get_contract_factory("CrowdsaleToken")

To    

      Contract = chain.provider.get_base_contract_factory("CrowdsaleToken")

... to see if it helps?

**Comment by gelinger777** [comment]
it helped but  now is this 

`------------------------------------------------------------
ValueError                 Traceback (most recent call last)
<ipython-input-2-9c876cf50050> in <module>()
     33     contract = Contract(address=contract_address)
     34     print("Attempting to release the token transfer")
---> 35     txid = contract.transact(transaction).releaseTokenTransfer()
     36     check_succesful_tx(web3, txid)
     37     print("Token released")

/usr/local/lib/python3.5/dist-packages/web3/contract.py in transact_with_contract_function(contract, function_name, transaction, *args, **kwargs)
    807     )
    808 
--> 809     txn_hash = contract.web3.eth.sendTransaction(transact_transaction)
    810     return txn_hash
    811 

/usr/local/lib/python3.5/dist-packages/eth_utils/string.py in inner(*args, **kwargs)
     83     @functools.wraps(fn)
     84     def inner(*args, **kwargs):
---> 85         return force_obj_to_text(fn(*args, **kwargs))
     86     return inner

/usr/local/lib/python3.5/dist-packages/web3/eth.py in sendTransaction(self, transaction)
    237             formatted_transaction['gas'] = get_buffered_gas_estimate(
    238                 self.web3,
--> 239                 transaction=formatted_transaction,
    240             )
    241         elif 'gas' not in formatted_transaction:

/usr/local/lib/python3.5/dist-packages/web3/utils/transactions.py in get_buffered_gas_estimate(web3, transaction, gas_buffer)
     45     gas_estimate_transaction = dict(**transaction)
     46 
---> 47     gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
     48 
     49     gas_limit = get_block_gas_limit(web3)

/usr/local/lib/python3.5/dist-packages/web3/utils/functional.py in inner(*args, **kwargs)
     12         @functools.wraps(fn)
     13         def inner(*args, **kwargs):
---> 14             value = fn(*args, **kwargs)
     15             return formatter(value)
     16         return inner

/usr/local/lib/python3.5/dist-packages/web3/eth.py in estimateGas(self, transaction)
    280         return self.web3._requestManager.request_blocking(
    281             "eth_estimateGas",
--> 282             [formatted_transaction],
    283         )
    284 

/usr/local/lib/python3.5/dist-packages/web3/providers/manager.py in request_blocking(self, method, params)
     49 
     50         if "error" in response:
---> 51             raise ValueError(response["error"])
     52 
     53         return response['result']

ValueError: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}

In [ ]:
`

**Comment by villesundell** [comment]
Basically, it means that releaseTokenTransfer() throws an exception (it's not very informative, granted ;) ).

You have to set your address as the releaseAgent by calling setReleaseAgent(address) as the owner (deployer of the token).

**Comment by gelinger777** [comment]
then it's related to #26  . Actually I have deployed without --release-agent option. Because I was gettin error when I was setting release agent. Without --release-agent it went throught. Could this be the problem? If yes, could you have a look at #26 ??

**Comment by gelinger777** [comment]
@villesundell  how to call calling setReleaseAgent(address)  ??? from which tool?

**Comment by gelinger777** [comment]
I am closing this issue. The problem is actually that the smart contract which is deployed with command 

deploy-token does not have release Functionality.
