### ISSUE TITLE
Jupyter error in use of release token 

### ISSUE THREAD

**Issue by waylonwu88** [TokenMarketNet/ico#35]
When I try to run the release token example on my machine, it shows 

ValueError: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}

Then I review the issue #30 found that I need to set my address to releaseAgent, but when I call
contract.transact(transaction).setReleaseAgent(owner_address), it shows the same error 

ValueError: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}

So when I look back in smart contract code, seems there is no restrictions but onlyOwner

function setReleaseAgent(address addr) onlyOwner inReleaseState(false) public {

    // We don't do interface check here as we might want to a normal wallet address to act as a release agent
    releaseAgent = addr;
  }

Since the address I own is the owner of the contract. So what should I do then?

**Comment by gelinger777** [comment]
This to be closed .I was trying to release a smart contract which   does not had Release functionality. Beforehand I thought that releasing is  a general functionality and had to work  with any contract

**Comment by gelinger777** [comment]
At #30 i was trying to relase simple token, which was from CentrallyIsuedToken.sol . That contract is deployed by default if contract name is not in the command while deploying. So IMHO you can't release the token which is deployed by simply making deploy-token --bla --bla

**Comment by gelinger777** [comment]
Are you deploying contract via deploy-token command or deploy-contracts ???

**Comment by waylonwu88** [comment]
I simply use deploy-token command.

**Comment by gelinger777** [comment]
that one does deploy the  CentrallyIssuedToken.sol which does not have releasing functionality. So simply it will not work to release.

**Comment by gelinger777** [comment]
have a look on contract 

deploy-contracts  and it's yaml file in crowdsales folder

**Comment by waylonwu88** [comment]
It works! Thanks @gelinger777

**Comment by gelinger777** [comment]
have  a nice day buddy :) I have suffered  hours on that problem.

**Comment by gelinger777** [comment]
close the ticket :)
