### ISSUE TITLE
simply won't connect to ropsten

### ISSUE THREAD

**Issue by pawanvs** [TokenMarketNet/ico#39]
Hello,

I am trying to connect to ropsten, any help in this direction appreciated.
I am using following command to connect
deploy-presale --chain ropsten --address=0x1b93a9de9B13D355D005167f89774DD98dbd7d3d --owner 0x1b93a9de9B13D355D005167f89774DD98dbd7d3d --days=-1 --minimum=0.001

I am timing out.

geth running with following arguments
geth --testnet --fast --nodiscover

and then I am attaching nodes as mentioned in 
https://github.com/ethereum/ropsten

Is there anyway I can run tokenmarketico on privatenet?

Regards,
P

**Comment by gelinger777** [comment]
did you activate the python venv?  You have to activate that as it is written in docs + when you run the command location should be the folder of ico. then it works

**Comment by gelinger777** [comment]
have a look on ports in populus.json too. But I am sure you did not activated virtual environment before running commands.

**Comment by miohtama** [comment]
Closing this as this has been addressed in the chat.
