### ISSUE TITLE
unable to run finalize stage

### ISSUE THREAD

**Issue by hsinhoyeh** [TokenMarketNet/ico#42]
hi, thanks for creating such good materials. I now can fully understand how ico actually works.
we run your deploy script successfully (with --address=$address1 [1]) but unable to run finalize stage (script[2]) because:
* the address we specified is owner address (i.e. $address1)
* but in your example.yml you have transferred the ownership into team_multisign.address [3]
* but I am unable to send transaction with the team_multisign.address due to the account does not exist.

btw If I removed onlyOwner modifier[4], it works for me without any problem.
Would you kindly guide me how to solve it? thanks

[1] https://github.com/TokenMarketNet/ico/blob/master/ico/cmd/deploycontracts.py
[2] https://gist.github.com/hsinhoyeh/d2336d450f221ccf8e942540f8ccdc66
[3] https://github.com/TokenMarketNet/ico/blob/master/crowdsales/example.yml#L158
[4] https://github.com/TokenMarketNet/ico/blob/master/contracts/Crowdsale.sol#L326

**Comment by miohtama** [comment]
team_multisig is indented to be a multisig wallet (Gnosis wallet) that controls the contracts.

Buy you can use any account as team_multisig address. E.g. the same address as deploy_address. 

I'll take this step away from `example.yml` and leave `deploy_address` as the release owner, so it is a more straightforward, working, example.

**Comment by miohtama** [comment]
See here https://github.com/TokenMarketNet/ico/commit/d1cabecc41938d2e42bf2b90aa5bac1acd02e0ef

**Comment by hsinhoyeh** [comment]
ya, if I use release owner as deploy_address, it works definitely.
but I just want to know the best practice to run an ICO, so team_multisign.address "should" be used?
