### ISSUE TITLE
Presale emergency hatch

### ISSUE THREAD

**Issue by miohtama** [TokenMarketNet/ico#45]
Make it possible to withdraw presale money to a multisig wallet in the case of an emergency.

**Comment by villesundell** [comment]
This was done in #58 (as fa7feed344554ccfd4e14d1920d0f6d941eacd6b):
The final implementation was forced state change to State.Refunding in case of problems (like technical problems or a failed ICO). This also provides some degree of investor safety especially before the crowdsale.
