### ISSUE TITLE
Deploy CrowdsaleToken and transfer lock issue

### ISSUE THREAD

**Issue by Brady0614** [TokenMarketNet/ico#46]
I hava a question about the CrowdsaleToken contract as folowing:

Assume I deploy the CrowdsaleToken(.sol) and lock the Token transfering that inherit the ReleasableToken(.sol).
Although the function::transfer()/transferFrom() in ReleasableToken is protected by modifier::canTransfer(), but the same ones from StandardToken that inherit from MintableToken is external and looks un-protected.
is possible called by any external approaches to StandardToken::transfer()/transferFrom() ?

	- contract CrowdsaleToken is ReleasableToken, MintableToken, UpgradeableToken { 
		... 
		function transfer() canTransfer ...
		function transferFrom() canTransfer ...
		
	  }

	- contract MintableToken is StandardToken, Ownable { ... }

	- contract StandardToken is ERC20, SafeMath {
	         ... 
		function transfer() ...  //external without protection? or set to internal?
		function transferFrom() ...  //the same above
	  }

**Comment by miohtama** [comment]
I am not sure if I understood " is possible called by any external approaches to StandardToken::transfer()/transferFrom() ?".

StandardToken doe not implement transfer lock up.

If the current contracts do not give you a good combination of features, you can always provide your own token contract that is used by the crowdsale.

**Comment by miohtama** [comment]
Closing this as there was no further feedback.
