### ISSUE TITLE
Problem with Deploy-Token

### ISSUE THREAD

**Issue by dogpatchmedia** [TokenMarketNet/ico#6]
Hi, im trying to test launch a token to the testnet and Ive followed all the steps in the documentation and I get errors:

Im using Python 3.5.3 on Ubuntu 14.04

Command:

deploy-token --chain=ropsten --address=0x3e66d224fc63B57327Bb6aFE885c39EC85F86bd3 --name="testtoken" --symbol=t5000 --release-agent=0x3e66d224fc63B57327Bb6aFE885c39EC85F86bd3  --supply=100000

Error:

Traceback (most recent call last):
  File "/usr/local/bin/deploy-token", line 9, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named ico.cmd.deploytoken

Any help is appreciated. Thanks.

**Comment by miohtama** [comment]
Hi @dogpatchmedia 

Something is a miss because it is using Python 2.7 libraries to run the command. See paths. Only Python versions 3.5+ are supported.

**Comment by dogpatchmedia** [comment]
Ah ok thanks. I will look into that and see what I can do to get it to use the right libraries.

**Comment by dogpatchmedia** [comment]
UPDATE: 

I guess if your system has more than one version of Python installed (ie, 2.7 and 3.5) you need to add the version number to pip. So its pip3.5 install <blah blah>. That tells it to use the 3.5 version and not the 2.7 version (which is what was happening to me). So Im happy to report that it works fine now. Thanks.

**Comment by miohtama** [comment]
@dogpatchmedia Yes. This depends on OS and distribution. Unfortunately there are no generic instructions for this and each platform must be covered separately.
