### ISSUE TITLE
'ExternalChain' object has no attribute 'get_contract_factory'

### ISSUE THREAD

**Issue by vkjdarop** [TokenMarketNet/ico#63]
After successfully deploying a crowdsale on ropsten testnet using a modified allocated-token-sale-example.yml, when trying to interact with the contracts via the jupyter notebook afterwards, the getattr calls to chain all fail with AtrributeError: 'ExternalChain' object has no attribute '(calledattribute)'.

The geth RPC connection is online, account unlock call works, Python version is 3.5.4. 
Any ideas?

**Comment by miohtama** [comment]
Hi,

There has been an API change in the recent version of Populus.

Please change any lines like:

        FractionalERC20 = chain.contract_factories.FractionalERC20

To:

      from ico.utils import get_contract_by_name
      FractionalERC20 = get_contract_by_name(chain, "FractionalERC20")

All PRs and issue reports on these welcome :)

**Comment by vkjdarop** [comment]
Confirmed tested, working and solved. Thanks
